WIDTH = 35
HEIGHT = 20
MAX_X = WIDTH - 2
MAX_Y = HEIGHT - 2
SNEK_LENGTH = 5
SNEK_X = SNEK_LENGTH + 1
SNEK_Y = 3
GOID_SIZE = 1
NUM_NEIGHBOURS = 3
SEPARATION_FACTOR = 1
COHERENCE_FACTOR = 1
# Screen refresh rate in milliseconds
TIMEOUT = 100
