WIDTH = 80
HEIGHT = 40
MAX_X = WIDTH - 2
MAX_Y = HEIGHT - 2
SNEK_LENGTH = 5
SNEK_X = SNEK_LENGTH + 1
SNEK_Y = 3
POID_SIZE = 1
POID_POPULATION = 20
NUM_NEIGHBOURS = 3
SEPARATION_FACTOR = float(POID_SIZE * 5)
COHERENCE_FACTOR = 1
# Screen refresh rate in milliseconds
TIMEOUT = 100
